Imbalanced dataset:

a dataset with unequal class distribution


in this example we will use an inbalaced dataset to make it balanced

dataset link :
https://drive.google.com/file/d/1WkcjUn5tVJDUtkN6d2_gztiT1FmIIVDP/view

In [5]:
#importing needed libraries
import pandas as pd
import numpy as np

In [6]:
#loading the dataset
credit_card_data = pd.read_csv('/content/credit_data.csv')

In [7]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [12]:
#distribution of data in the 2 classes
credit_card_data['Class'].value_counts()

0.0    207641
1.0       393
Name: Class, dtype: int64

as we see the data is imbalaced

1----> fraudlent transactions

0----> normal/legit transactions

In [14]:
#separiting the legit and fraudlent transactions
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class ==1]

In [15]:
print(legit.shape)
print(fraud.shape)

(207641, 31)
(393, 31)

under-sampling

we will build a sample dataset containinig similar distribution of legit and fraudlent transcations


the number of legit transactions is 492

In [17]:
legit_sample = legit.sample(n=492)
print(legit_sample.shape)

(492, 31)

In [18]:
new_dataset = pd.concat([legit_sample, fraud] , axis= 0)

In [19]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
136708,81830.0,1.061140,-0.636756,-0.453465,0.103950,0.048045,0.457634,0.017189,0.033625,-1.434709,...,-0.657039,-1.798790,-0.034464,-1.253793,0.286595,-0.670644,0.011317,0.029616,157.69,0.0
202239,134233.0,2.078138,0.134353,-1.731924,0.408225,0.414024,-0.857830,0.164103,-0.215950,0.543660,...,-0.371498,-0.979503,0.336661,0.473653,-0.261346,0.175962,-0.064795,-0.031608,1.98,0.0
59388,48817.0,-1.537050,1.285310,0.610591,-0.176403,0.791767,-1.563499,0.997854,-0.096316,-0.736737,...,-0.087934,-0.306934,-0.161836,0.258375,0.621490,0.237708,-0.599648,-0.122238,0.76,0.0
41593,40750.0,1.292058,-1.176490,0.476944,-1.299234,-1.338491,-0.239934,-0.929313,-0.050408,-1.991187,...,-0.091573,0.095952,0.073516,0.094875,0.197534,-0.176136,0.056805,0.029614,74.35,0.0
172172,120987.0,2.035698,-0.060562,-1.853927,0.256825,0.444161,-0.428091,-0.038465,0.032583,0.534086,...,-0.348691,-1.042728,0.305762,0.135490,-0.314418,0.177875,-0.080566,-0.046176,9.99,0.0

In [20]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
203328,134769.0,-0.967767,2.098019,-5.222929,6.514573,-4.187674,2.114178,0.948701,-2.448427,-3.203666,...,-0.843268,0.796739,1.314312,-0.352887,-1.770706,0.098133,0.956769,0.162777,925.31,1.0
203700,134928.0,1.204934,3.238070,-6.010324,5.720847,1.548400,-2.321064,-0.781880,0.076619,-2.976249,...,0.098341,-0.845866,-0.031228,0.421146,0.388361,0.056035,0.491828,0.340847,0.00,1.0
204064,135095.0,0.232512,0.938944,-4.647780,3.079844,-1.902655,-1.041408,-1.020407,0.547069,-1.105990,...,0.911373,1.042929,0.999394,0.901260,-0.452093,0.192959,0.180859,-0.029315,345.00,1.0
204079,135102.0,1.862102,-0.124052,-1.989752,0.382609,0.473032,-0.674517,0.298621,-0.282416,0.802053,...,-0.204158,-0.511441,0.077874,0.388335,0.007896,-0.120980,-0.019579,0.006155,108.51,1.0
204503,135314.0,-3.158990,1.765452,-3.390168,0.987410,-1.509930,-1.280952,-2.719557,0.718325,-1.660183,...,1.120533,1.605085,-0.618637,-0.251283,-0.240528,-0.004327,-0.235477,0.018129,84.28,1.0

In [21]:
new_dataset['Class'].value_counts()

0.0    492
1.0    393
Name: Class, dtype: int64

as we see we balanced the data (we can take equal numbers ) but i decided to make the values closer to each other